version: '3.9'
services:
  devcontainer:
    container_name: gh-pages-devcontainer
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye
    volumes:
      - ../:/app:cached
    command: sleep infinity
